import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nabvar from "./components/Nabvar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nabvar></Nabvar>
        <main className="h-screen h-max-[800px]">
          {children}
        </main>
        <footer className="text-center bg-slate-700"> Awesome next js project</footer>
      </body>
    </html>
  );
}
