import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nabvar from "./components/Nabvar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nabvar></Nabvar>
        <main className="min-h-screen px-4 py-8">{children}</main>
        <footer className="bg-slate-800 text-white py-6 mt-10">
          <div className="max-w-6xl mx-auto text-center">
            <p className="text-lg font-medium">🚀 Awesome Next.js Project</p>
            <p className="text-sm text-gray-300 mt-2">
              © {new Date().getFullYear()} All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
